#!/bin/bash
PROG=./clox

tests=$(find tests -type f)

total=0
pass=0
failed_tests=()
for t in $tests; do
  echo "$t"...
  $PROG "$t" >/dev/null
  if [[ $? -eq 0 ]]; then
    pass=$((pass + 1))
  else
    failed_tests+=("$t")
  fi
  total=$((total + 1))
done

failed=$((total - pass))

if [[ $total -ne $pass ]]; then
  echo
  echo "$(tput setaf 1)Failed tests:"
fi

for t in "${failed_tests[@]}"; do
  echo "$(tput setaf 1)$t"
done

echo
echo "$(tput setaf 2)$pass passed, $(tput setaf 1)$failed failed"

tput setaf 0
